# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06c54e963abd3ddc39b6b7a8299bffbcd65d4523c5aca7f49d79ec7306f89243e7766093f4f907120ba742c1fccef090166589feabb34503969f61064141782d

test:
  secret_key_base: badd05af92f2c80e0c4036050af4a5e5b59f1434f68f9e69513ebb5ff2c099e47ae7af2f187c40724bf095f3071e5d5c5bb2551cbc9c5df86c3754a6ff560255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
